# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 78d3f68df3ad08ef720139ef80aaeeaac6b276973c7a2bb30ceb8170cd71c284d51a102809a4c20a289f084f3626184b4c2bac289e10b2355e9d252e8a9f0e05

test:
  secret_key_base: 5fcd823a5551fb3e759cbaf90df17063115153e0f0be097fe91c29d8047ef547ea295a22aa09a6616799c1638b487f4fbc238080e9a58a17342c453e2191edbd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
